- hosts: isucon
  become: yes
  vars:
    isucon_user: "isucon"
  vars_files:
    - vars/vault_secret.yml
  roles:
    - { name: base/packages }
    - { name: base/tools }
    - { name: base/user }
    - { name: notify_slack }
    - { name: gist }

