- name: exists /usr/local/slackboard
  file:
    path: /usr/local/slackboard
    state: directory

- name: copy slackboard archive
  copy:
    src: slackboard_linux_generic.tgz
    dest: /usr/local/src/slackboard.tgz

- name: extract slackboard binary
  unarchive:
    src: /usr/local/src/slackboard.tgz
    dest: /usr/local/slackboard
    mode: 0755
    owner: root
    group: root

- name: link /usr/local/bin/slackboard-cli
  file:
    src: /usr/local/slackboard/bin/slackboard-cli
    dest: /usr/local/bin/slackboard-cli
    state: link

# --- set config
- name: exists /etc/slackboard
  file:
    path: /etc/slackboard
    state: directory

- name: copy slackboard config
  template:
    src: etc/slackboard/slackboard.toml.j2
    dest: /etc/slackboard/slackboard.toml

- name: exists /usr/lib/systemd/system
  file:
    path: /usr/lib/systemd/system
    state: directory
    recurse: true

- name: copy systemd service unit
  copy:
    src: usr/lib/systemd/system/slackboard.service
    dest: /usr/lib/systemd/system/slackboard.service
    owner: root
    group: root

- name: start slackboard
  systemd:
    name: slackboard
    state: started
    daemon_reload: true

